@echo off
setlocal
set "NINO_ROOT=%~dp0"
if "%NINO_ROOT:~-1%"=="\" set "NINO_ROOT=%NINO_ROOT:~0,-1%"
set "NINO_DATA_ROOT=D:\runtime\profiles\nino"
set "NINO_APPDATA_ROOT=%NINO_DATA_ROOT%\appdata"
set "PYTHONUTF8=1"
set "PYTHONUSERBASE=D:\runtime\python-userbase"
set "PIP_CACHE_DIR=D:\cache\pip"
set "PIP_CONFIG_FILE=D:\config\pip\pip.ini"
set "PYTHONPYCACHEPREFIX=D:\cache\python\pycache"
set "TEMP=D:\temp\python\nino"
set "TMP=D:\temp\python\nino"
set "PATH=D:\venvs\nino\Scripts;D:\tools\python\tools;D:\tools\node;D:\tools\node-global;%PATH%"
set "NPM_CONFIG_PREFIX=D:\tools\node-global"
set "NPM_CONFIG_CACHE=D:\cache\npm"
set "NPM_CONFIG_USERCONFIG=D:\config\npm\npmrc"
set "APPDATA=%NINO_APPDATA_ROOT%\Roaming"
set "LOCALAPPDATA=%NINO_APPDATA_ROOT%\Local"
if not exist "%NINO_DATA_ROOT%" mkdir "%NINO_DATA_ROOT%"
if not exist "%TEMP%" mkdir "%TEMP%"
if not exist "%APPDATA%" mkdir "%APPDATA%"
if not exist "%LOCALAPPDATA%" mkdir "%LOCALAPPDATA%"
"D:\venvs\nino\Scripts\python.exe" "%NINO_ROOT%\main.py"
set "NINO_EXIT=%ERRORLEVEL%"
endlocal & exit /b %NINO_EXIT%
